app/auth.py
from flask import Blueprint, flash, request, render_template, session, redirect, url_for
from app.validators import validate_email, validate_password, validate_phone_number
from .models import User
from flask_login import login_required, login_user, logout_user, current_user
from .import db
from .validators import send_email_otp, generate_otp, verify_otp
from .services import create_wallet_with_retries

# blueprint definition
auth = Blueprint("auth", __name__)

# a welcome route
@auth.route("/", methods=['POST', 'GET'])
def welcome():
    return render_template("auth_templates/welcome.html")


# six authentication routes
# 1 pre authentication route
@auth.route("/pre-auth", methods=['POST', 'GET'])
def pre_auth():
    return render_template("auth_templates/pre_auth.html")

# 2 sign up route
@auth.route("/sign-up", methods=['POST', 'GET'])
def sign_up():
    if request.method == 'POST':

        # grab the user data
        full_name = request.form.get("full_name")
        username = request.form.get("username")
        email = request.form.get("email")
        phone_number = request.form.get("phone_number")
        referral_username = request.form.get("referral_username")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        # lets store form data in a session
        session['full_name'] = full_name
        session['username'] = username
        session['email'] = email
        session['phone_number'] = phone_number
        session['referral_username'] = referral_username

        user_username = User.query.filter_by(email=username).first()
        user_email = User.query.filter_by(username=email).first()

        # checks if the input field are empty
        if not full_name or not username or not email or not phone_number or not password1 or not password2:
            flash("All fields are required except for referral username", category="error")
            return render_template('auth_templates/sign_up.html')

        # check if username or email already exists
        elif user_username:
            flash("Username already exists", category="error")
            return render_template('auth_templates/sign_up.html')

        elif user_email:
            flash("Email already exists", category="error")
            return render_template('auth_templates/sign_up.html')


        # check if name is valid
        elif not full_name.isalpha() or not full_name.strip():
            flash("Name must contain only alphabetic characters", category="error")
            return render_template('auth_templates/sign_up.html')

        elif len(full_name) < 3:
            flash("Name must be at least 3 characters long", category="error")
            return render_template('auth_templates/sign_up.html')

        # check if username is valid
        elif not username.isalnum() or not username.strip():
            flash("Username must contain only alphanumeric characters", category="error")
            return render_template('auth_templates/sign_up.html')
        elif len(username) < 5:
            flash("Username must be at least 5 characters long", category="error")
            return render_template('auth_templates/sign_up.html')

        # check if email is valid
        elif not validate_email(email):
            flash("Invalid email address", category="error")
            return render_template('auth_templates/sign_up.html')

        # check if phone number is valid
        elif not validate_phone_number(phone_number):
            flash("Invalid phone number format, use country code format", category="error")
            return render_template('auth_templates/sign_up.html')

        # check if passwords match
        elif password1 != password2:
            flash("Passwords do not match", category="error")
            return render_template('auth_templates/sign_up.html')
        elif len(password1) < 8:
            flash("Password must be at least 8 characters long", category="error")
            return render_template('auth_templates/sign_up.html')
        elif not validate_password(password2):
            flash("Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character", category="error")
            return render_template('auth_templates/sign_up.html')
        else:
            # checks if referral exists in users
            referral = User.query.filter_by(username=referral_username).first()
            if not referral:
                flash("Referral username doesn't exist!", category="info")
            referral_username = referral_username

            # clear the session data
            session.clear()

            # create a new user
            new_user = User()
            new_user.set_name(full_name)
            new_user.set_username(username)
            new_user.set_email(email)
            new_user.set_password(password2)
            new_user.set_phone_number(phone_number)
            new_user.referred_by = referral_username
            db.session.add(new_user)
            db.session.commit()

            # create api wallet for the user
            response = create_wallet_with_retries(new_user)
            if response["success"]:
                # save the api wallet id to the database
                new_user.api_wallet_id = response["wallet_id"]
                db.session.commit()

            # login the user after signing up
            login_user(new_user)
            return render_template("main_templates/main_dashboard.html")
    return render_template("auth_templates/sign_up.html")

# 3 login route
@auth.route("/login", methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        # grab the form data
        username = request.form.get('username_or_email')
        password = request.form.get('password')

        # let add form data to the session
        session['username'] = username

        # check if the fields are empty
        if not username or not password:
            flash('All fields are required', category="error")
            return render_template('auth_templates/login.html')

        # check if user exists
        # login with username and password
        user_with_username = User.query.filter_by(username=username).first()
        if user_with_username and user_with_username.check_password(password):
            flash('Login successful', category="success")
            # clear the session
            session.clear()
            login_user(user_with_username)
            return render_template("main_templates/main_dashboard.html")

        # login with email and password
        elif not user_with_username:
            user_with_email = User.query.filter_by(email=username).first()
            if user_with_email and user_with_email.check_password(password):
                flash('Login successful', category="success")
                # clear the session data
                session.pop('username', None)
                # clear the session
                session.clear()
                login_user(user_with_email)
                return render_template("main_templates/main_dashboard.html")
        else:
            flash('Invalid username or password', category="error")
            return render_template("auth_templates/login.html")
    return render_template("auth_templates/login.html")

# 4 logout route (additional route ( it's non-template rendering ))
@auth.route("/logout", methods=['POST', 'GET'])
@login_required
def logout():
    # clear the session
    session.clear()
    logout_user()
    return render_template("auth_templates/pre_auth.html")

# 5 password forgotten route (find account, request otp and reset password)
@auth.route("/reset-password", methods=['POST', 'GET'])
def reset_password():
    if request.method == 'POST':
        username = request.form.get('username_or_email')
        session['username'] = username

        if not username:
            flash('enter your username or email', category='error')
            return render_template('auth_templates/reset_password.html')

        user_by_email = User.query.filter_by(email=username).first()
        user_by_username = User.query.filter_by(username=username).first()

        # first form to find the account using email or username then request for otp
        if 'username_submit_btn' in request.form:
            if user_by_email:
                otp = generate_otp(5)  # generate otp
                session['otp'] = otp  # save it to session
                send_email_otp(user_by_email.email, otp)  # send it to user email
                flash('otp sent to your email', category='success')
            elif user_by_username:
                otp = generate_otp(5)  # generate otp
                session['otp'] = otp  # save it to session
                send_email_otp(user_by_email.email, otp)  # send it to user email
                flash('otp sent to your email', category='success')
            elif not user_by_username:
                flash("account with this username doesn't exist", category='error')
                return render_template('auth_templates/reset_password.html')
            elif not user_by_email:
                flash("account with this email doesn't exist", category='error')
                return render_template('auth_templates/reset_password.html')

            user_otp = request.form.get('otp')
            session['user_otp'] = user_otp

            if verify_otp(user_otp):
                flash('otp verified', category='success')
                return redirect(url_for('auth.reset_password'))
            else:
                flash('invalid otp', category='error')
                return render_template('auth_templates/reset_password.html')

        # second form to reset the password
        if 'password_submit_btn' in request.form:
            password1 = request.form.get('password1')
            password2 = request.form.get('password2')

app/templates/auth_templates/auth_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='css/auth_style.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    <!-- auth content block  -->
    {% block content %}
    {% endblock %}

    <!-- script to achieve re-usabilities -->
    <script>
        // Function to toggle password visibility
        function togglePasswordVisibility(passwordFieldId, iconId) {
            // Select the password field and the icon
            const passwordField = document.getElementById(passwordFieldId);
            const toggleIcon = document.getElementById(iconId);

            // Toggle the type of the password field
            const type = passwordField.getAttribute("type") === "password" ? "text" : "password";
            passwordField.setAttribute("type", type);

            // Toggle the icon class
            toggleIcon.classList.toggle("fa-eye");
            toggleIcon.classList.toggle("fa-eye-slash");
        }
    </script>
    
</body>
</html>

app/templates/auth_templates/change_password.html
{% extends 'auth_templates/auth_base.html' %}

{% block title %}
    generate new password
{% endblock %}

{% block content %}
    <div class="auth-wrapper">
        <div class="auth-box">
            <div class="back-btn-container">
                <button class="get-back-btn" name="username_submit_btn" onclick="history.back()">
                    <i class="fas fa-chevron-left" style="font-size: 24px;"></i>
                </button>
                <div class="auth-heading">
                    <h2><strong>Resetting password</strong></h2>
                </div>
            </div>
            <!-- to show flashed messages -->
            {% with messages = get_flashed_messages( with_categories = true )%}
                {% if messages %}
                    <ul>
                        {% for category, message in messages %}
                            <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
            <div class="auth-box-p">
                <p class="have-account">Changing password</p>
            </div>
            <div class="auth-form">
                <form method="POST">
                    <div class="input-container">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input type="password" id="old_password" name="old_password" placeholder="Old password">
                        <i class="fas fa-eye-slash" id="togglePassword1" onclick="togglePasswordVisibility('old_password', 'togglePassword1')"></i>
                    </div>
                    <div class="input-container">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input type="password" id="password1" name="password1" placeholder="New password">
                        <i class="fas fa-eye-slash" id="togglePassword2" onclick="togglePasswordVisibility('password1', 'togglePassword2')"></i>
                    </div>
                    <div class="input-container">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input type="password" id="password2" name="password2" placeholder="Re-enter password">
                        <i class="fas fa-eye-slash" id="togglePassword3" onclick="togglePasswordVisibility('password2', 'togglePassword3')"></i>
                    </div>
                    <div class="submit-container">
                        <button type="submit" class="submit-btn" name="password_submit_btn">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/auth_templates/change_pin.html
{% extends 'auth_templates/auth_base.html' %}

{% block title %}
    Change of pin
{% endblock %}

{% block content %}
    <div class="auth-wrapper">
        <div class="auth-box">
            <div class="back-btn-container">
                <button class="get-back-btn" name="username_submit_btn" onclick="history.back()">
                    <i class="fas fa-chevron-left" style="font-size: 24px;"></i>
                </button>
                <div class="auth-heading">
                    <h2><strong>Change Of Pin</strong></h2>
                </div>
            </div>
            <!-- to show flashed messages -->
            {% with messages = get_flashed_messages( with_categories = true )%}
                {% if messages %}
                    <ul>
                        {% for category, message in messages %}
                            <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
            <div class="auth-box-p">
                <p class="have-account">Changing pin</p>
            </div>
            <div class="auth-form">
                <form method="POST">
                    <!-- <p style="font-size:13px;"></p> -->
                    <div class="input-container">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input 
                            type="password" 
                            id="old_pin" 
                            maxlength="4" 
                            pattern="\d{4}" 
                            placeholder="Enter 4-digit PIN" 
                            title="Please enter exactly 4 digits" 
                            required>
                        <i class="fas fa-eye-slash" id="togglePassword" onclick="togglePasswordVisibility('old_pin', 'togglePassword')"></i>
                    </div>
                    <div class="input-container">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input
                            type="password" 
                            id="new_pin1" 
                            maxlength="4" 
                            pattern="\d{4}" 
                            placeholder="Enter 4-digit PIN" 
                            title="Please enter exactly 4 digits" 
                            required>
                        <i class="fas fa-eye-slash" id="togglePassword1" onclick="togglePasswordVisibility('new_pin1', 'togglePassword1')"></i>
                    </div>
                    <div class="input-container ">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input 
                            type="password" 
                            id="new_pin2" 
                            maxlength="4" 
                            pattern="\d{4}" 
                            placeholder="Enter 4-digit PIN" 
                            title="Please enter exactly 4 digits" 
                            required>
                        <i class="fas fa-eye-slash" id="togglePassword2" onclick="togglePasswordVisibility('new_pin2', 'togglePassword2')"></i>
                    
                    </div>
                    <div class="submit-container">
                        <button type="submit" class="submit-btn" name="password_submit_btn">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/auth_templates/login.html
{% extends 'auth_templates/auth_base.html' %}

{% block title %}
    login
{% endblock %}

{% block content %}
    <div class="auth-wrapper">
        <div class="auth-box">
            <div class="back-btn-container">
                <button class="get-back-btn" name="username_submit_btn" onclick="history.back()">
                    <i class="fas fa-chevron-left" style="font-size: 24px;"></i>
                </button>
                <div class="auth-heading">
                    <h2><strong>Welcome back!</strong></h2>
                </div>
            </div>
            <!-- to show flashed messages -->
            {% with messages = get_flashed_messages( with_categories = true )%}
                {% if messages %}
                    <ul>
                        {% for category, message in messages %}
                            <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
            <div class="auth-box-p">
                <p class="have-account">Log in to your account</p>
            </div>
            <form class="auth-form" method="post">
                <div class="input-container">
                    <i class="fas fa-user" style="color: #06283D; font-size: 24px;"></i>
                    <input 
                        type="text" 
                        class="input" 
                        placeholder="Username Or Email" 
                        id="username" 
                        name="username_or_email"
                        value="{{ session['username'] }}">
                </div>
                <div class="input-container">
                    <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                    <input 
                        type="password" 
                        class="input" 
                        placeholder="Password" 
                        id="password" 
                        name="password">
                    <i class="fas fa-eye-slash" id="togglePassword" onclick="togglePasswordVisibility('password', 'togglePassword')"></i>
                </div>
                <div class="submit-container">
                    <button type="submit" class="submit-btn">Login</button>
                </div>
                <div>
                    <p class="have-account"><a class="term" href="/reset-password">Forget Password</a></p>
                    <p class="have-account">You don't have account? <a class="term" href="/sign-up">Sign Up</a></p>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

app/templates/auth_templates/pre_auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login/signup</title>
    <style>
        body {
            height: 100vh;
            margin: 0;
            padding: 0;
        }
        .pre-auth-wrapper {
            background-image: url('../static/images/other_images/pre_auth.jpg');
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            background-repeat: no-repeat;
            box-sizing: border-box;
            font-family: 'Poppins';
            display: flex;
            justify-content: center;
            min-height: 100vh;
            width: 100%;
        }
        .pre-auth-container {
            align-items: center;
            border-radius: 20px;
            display: flex;
            flex-direction: column;
            height: auto;
            justify-content: center;
            margin-bottom: 30px;
            margin-top: 30px;
            padding: 20px;
            width: 70%;
        }
        .pre-auth-container p {
            width: 50%;
        }
        /* .pre-auth-icon {
            align-items: center;
            border: none;
            height: 100px;
            margin-top: 10px;
            margin: 20px;
            width: 100px;
        } */
        .pre-auth-heading {
            color: #256D85;
            font-size: 1.5rem;
            font-weight: 300;
            margin-top: 10px;
        }
        .pre-auth-brand {
            color: #256D85;
            font-size: 2rem;
            font-weight: bolder;
            margin-top: -10px;
            text-align: center;
        }
        .pre-auth-paragraph {
            color: #256D85;
            font-size: 1.2rem;
            margin-top: 20px;
            padding: 20px;
            text-align: center;
            width: 60%;
        }
        .pre-auth-btn-container {
            display: flex;
            gap: 20px;
            justify-content: center;
            margin-bottom: 20px;
            margin-top: 20px;
            width: 100%;
        }
        .pre-auth-btn-container  button {
            border-radius: 10px;
            cursor: pointer;
            display: inline-block;
            font-size: 17px;
            font-weight: bold;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            transition: background-color 0.3s ease;
            width: 30%;
        }
        .pre-auth-sign-up-btn {
            border: none;
            background-color: #256D85;
            color: #fff;
        }
        .pre-auth-login-btn {
            background-color: transparent;
            border: 0.5px, solid #256D85;
            color: #256D85;
        }
        .have-account {
            color: #256D85;
            font-size: 17px;
            text-align: center;
        }

        @media (max-width: 689px) {
            .pre-auth-btn-container {
                display: flex;
                justify-content: center; 
                gap: 10px;
                margin-bottom: 20px;
                margin-top: 20px;
                width: 40%;
            }
            .pre-auth-btn-container button {
                width: 100%;
            }
            .pre-auth-container p {
                width: 100%;
            }
        }
    </style>
</head>
<body>
    <div class="pre-auth-wrapper">
        <div class="pre-auth-container">
            <img height="150" src="{{url_for('static', filename='../static/images/other_images/start_whitelogo.png')}}" alt="" class="pre-auth-icon">
            <h3 class="pre-auth-heading">
                Welcome To:
            </h3>
            <h1 class="pre-auth-brand">
                DataVista
            </h1> 
    
            <p class="have-account">
                All our concern remain looking forward to provide fast, simple and reliable virtual top up platform with better experience.
                <br>
                <br>
                Lets top it up...
            </p>
            <div class="pre-auth-btn-container">
                <button class="pre-auth-sign-up-btn" type="submit" onclick="location.href='/sign-up'">SignUp</button>
                <button class="pre-auth-login-btn"type="submit" onclick="location.href='/login'">LogIn</button>
            </div>
        </div>
    </div>
</body>
</html>

app/templates/auth_templates/reset_password.html
{% extends 'auth_templates/auth_base.html' %}

{% block title %}
    forgot password
{% endblock %}

{% block content %}
    <div class="auth-wrapper">
        <div class="auth-box">
            <div class="back-btn-container">
                <button class="get-back-btn" name="username_submit_btn" onclick="history.back()">
                    <i class="fas fa-chevron-left" style="font-size: 24px;"></i>
                </button>
                <div class="auth-heading">
                    <h2><strong>Forgetting Password</strong></h2>
                </div>
            </div>
            <!-- to show flashed messages -->
            {% with messages = get_flashed_messages( with_categories = true )%}
                {% if messages %}
                    <ul>
                        {% for category, message in messages %}
                            <li class="{{ category }}">{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endwith %}
            <div class="auth-box-p">
                <p class="have-account">Get otp verification</p>
            </div>
            <div class="auth-form">
                <form method="POST">
                    <div class="input-container">
                        <i class="fas fa-user" style="color: #06283D; font-size: 24px;"></i>
                        <input 
                            type="text" 
                            id="username" 
                            name="username_or_email" 
                            placeholder="Username Or Email"
                            value="{{ session['username'] }}"
                            >
                    </div>
                    <div class="input-container">
                        <i class="fas fa-shield" style="color: #06283D; font-size: 24px;"></i>
                        <input 
                            type="text" 
                            id="otp" 
                            name="otp" 
                            placeholder="OTP"
                            >
                        <button class="get-code-btn" name="username_submit_btn">Get code</button>
                    </div>
                    <p class="have-account" style="text-align: left; margin-left: 7px;">Change the password</p>
                    <div class="input-container">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input 
                            type="password" 
                            id="password1" name="password1" 
                            placeholder="New password"
                            >
                        <i class="fas fa-eye-slash" id="togglePassword1" onclick="togglePasswordVisibility('password1', 'togglePassword1')"></i>
                    </div>
                    <div class="input-container">
                        <i class="fas fa-lock" style="color: #06283D; font-size: 24px;"></i>
                        <input 
                            type="password" 
                            id="password2" 
                            name="password2" 
                            placeholder="Re-enter new password"
                            >
                        <i class="fas fa-eye-slash" id="togglePassword2" onclick="togglePasswordVisibility('password2', 'togglePassword2')"></i>
                    </div>
                    <div class="submit-container">
                        <button type="submit" class="submit-btn" name="password_submit_btn">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/auth_templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <title>welcome</title>

    <style>
        body {
            background-color: #256D85;
            color: #fff;
            font-family: 'Poppins';
            display: flex;
            flex-direction: column;
            gap: 30px;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .loader-container {
            text-align: center;
        }
        .fa-spinner {
            font-size: 3rem;
            color: #fff;
            animation: spin 1.5s linear infinite;
        }
        @keyframes spin {
            from {
                transform: rotate(0deg);
            }
            to {
                transform: rotate(360deg);
            }
        }
    </style>
   <script>
        document.addEventListener("DOMContentLoaded", function () {
            setTimeout(function () {
                // Redirect to the home page after 3 seconds
                window.location.href = "{{ url_for('auth.pre_auth') }}";
            }, 3000);
        });
    </script>
</head>
<body> 
    <div class="img-container">
        <img height="250" src="{{ url_for('static', filename='images/other_images/start_whitelogo.png')}}" alt="">
    </div>  
    <div class="loader-container">
        <i class="fas fa-spinner"></i>
        <!-- <p>Loading, please wait...</p> -->
    </div>
</body>
</html>